#!/bin/bash
users>~/lan/usuarios
while IFS= read -r line; do usuario=$line; done < ~/lan/usuarios
echo ''>/home/$usuario/.config/polybar/scripts/lan/lan.view
echo ''>/home/$usuario/.config/polybar/scripts/lan/wan.view
echo ''>/home/$usuario/.config/polybar/scripts/lan/vpn.view
monitor(){
proceso=$(ps -e | grep openvpn | awk '{print $4}') #> /dev/null 2>&1)
IFACE=$(/usr/sbin/ifconfig | grep tun0 | awk '{print $1}' | tr -d ':')
if [ "$proceso" ]
then
      	#echo hay openvpn> /dev/null 2>&1;
	      bash -c "sudo killall openvpn"
        bash -c "sudo ip link delete tun0"
else
   	    echo no hay openvpn> /dev/null 2>&1
	
fi
}
for (( ; ; ))
do
clear
if ping -c1 google.com &>/dev/null; then
	echo tengo internet> /dev/null 2>&1	
	proceso2=$(ps -e | grep n.sh | awk '{print $4}') > /dev/null 2>&1;
		if $proceso2> /dev/null 2>&1;	then
			cd ~/lan && bash -c "./lan.sh &"
			cd ~/lan && bash -c "./wan.sh &"
			cd ~/lan && bash -c "./vpn.sh &"
		fi	
#./vpn.sh
else 
	echo no tengo internet> /dev/null 2>&1
	monitor
	killall *n.sh> /dev/null 2>&1
	#Aqui debes cambiar el nombre de <usuario> por tu usuario para ello debes usar el comando whoami para saber cual es tu usuario
	#cd /home/$usuario/.config/polybar/scripts/lan
	echo	"Desconectado">/home/$usuario/.config/polybar/scripts/lan/lan.view
	echo	"Desconectado">/home/$usuario/.config/polybar/scripts/lan/wan.view
	echo	"Desconectado">/home/$usuario/.config/polybar/scripts/lan/vpn.view
fi
#monitor
sleep 3s
done
